/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/test/test-component';
import * as i2 from '../at-grid/at-grid.ngfactory';
import * as i3 from '../../../../src/app/at-grid/at-grid';
const styles_TestComponent:any[] = ([] as any[]);
export const RenderType_TestComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TestComponent,data:{}});
export function View_TestComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),
      (null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.TestComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.add()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Добавить'])),
      (_l()(),i0.ɵted((null as any),['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'at-grid',([] as any[]),(null as any),(null as any),(null as any),i2.View_AtGrid_0,
          i2.RenderType_AtGrid)),i0.ɵdid(8503296,(null as any),0,i3.AtGrid,([] as any[]),
          {data:[0,'data'],metaData:[1,'metaData']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i1.TestComponent = _v.component;
    const currVal_0:any = _co.data;
    const currVal_1:any = _co.columns;
    _ck(_v,4,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_TestComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'test-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_TestComponent_0,
      RenderType_TestComponent)),i0.ɵdid(8503296,(null as any),0,i1.TestComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TestComponentNgFactory:i0.ComponentFactory<i1.TestComponent> = i0.ɵccf('test-component',
    i1.TestComponent,View_TestComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29yay91c3Ivd3d3L3RlbXBsYXRlLWFwcGxpY2F0aW9uL3NyYy9hcHAvdGVzdC90ZXN0LWNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Xb3JrL3Vzci93d3cvdGVtcGxhdGUtYXBwbGljYXRpb24vc3JjL2FwcC90ZXN0L3Rlc3QtY29tcG9uZW50LnRzIiwibmc6Ly8vQzovV29yay91c3Ivd3d3L3RlbXBsYXRlLWFwcGxpY2F0aW9uL3NyYy9hcHAvdGVzdC90ZXN0LWNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovV29yay91c3Ivd3d3L3RlbXBsYXRlLWFwcGxpY2F0aW9uL3NyYy9hcHAvdGVzdC90ZXN0LWNvbXBvbmVudC50cy5UZXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGJ1dHRvbiAoY2xpY2spPVwiYWRkKClcIj7QlNC+0LHQsNCy0LjRgtGMPC9idXR0b24+XHJcblxyXG48YXQtZ3JpZFxyXG4gIFtkYXRhXT1cImRhdGFcIlxyXG4gIFttZXRhRGF0YV09XCJjb2x1bW5zXCJcclxuPjwvYXQtZ3JpZD5cclxuIiwiPHRlc3QtY29tcG9uZW50PjwvdGVzdC1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO1FBQUE7UUFBQTtRQUFRO1VBQUE7VUFBQTtRQUFBO1FBQVI7TUFBQSxnQ0FBd0I7TUFBaUIseUNBRXpDO1VBQUE7OEJBQUEsVUFBQTtVQUFBLHlEQUdXO1VBQUE7O0lBRlQ7SUFDQTtJQUZGLFdBQ0UsVUFDQSxTQUZGOzs7O29CQ0ZBO01BQUE7OEJBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
