/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/test/test-component';
const styles_TestComponent:any[] = ([] as any[]);
export const RenderType_TestComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TestComponent,data:{}});
export function View_TestComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['test-component'])),(_l()(),i0.ɵted((null as any),['\n']))],
      (null as any),(null as any));
}
export function View_TestComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'test-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_TestComponent_0,
      RenderType_TestComponent)),i0.ɵdid(49152,(null as any),0,i1.TestComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const TestComponentNgFactory:i0.ComponentFactory<i1.TestComponent> = i0.ɵccf('test-component',
    i1.TestComponent,View_TestComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29yay91c3Ivd3d3L3RlbXBsYXRlLWFwcGxpY2F0aW9uL3NyYy9hcHAvdGVzdC90ZXN0LWNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Xb3JrL3Vzci93d3cvdGVtcGxhdGUtYXBwbGljYXRpb24vc3JjL2FwcC90ZXN0L3Rlc3QtY29tcG9uZW50LnRzIiwibmc6Ly8vQzovV29yay91c3Ivd3d3L3RlbXBsYXRlLWFwcGxpY2F0aW9uL3NyYy9hcHAvdGVzdC90ZXN0LWNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovV29yay91c3Ivd3d3L3RlbXBsYXRlLWFwcGxpY2F0aW9uL3NyYy9hcHAvdGVzdC90ZXN0LWNvbXBvbmVudC50cy5UZXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+dGVzdC1jb21wb25lbnQ8L3A+XHJcbiIsIjx0ZXN0LWNvbXBvbmVudD48L3Rlc3QtY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSxvQ0FBa0I7Ozs7b0JDQXJCO01BQUE7OEJBQUEsVUFBQTtNQUFBOzs7In0=
